export * from "./hooks/arithmetic";
export * from "./hooks/evenOdd";
export * from "./hooks/permut-combi";
export * from "./hooks/primeNumber";
export * from "./hooks/palindromeNumber";
export * from "./hooks/reverseNumber";
export * from "./hooks/multiplication";
export * from "./hooks/digitOfNumber";
export * from './hooks/armstrongNumber';